--Pais
INSERT INTO TBG_PAIS (PAIS_ID,PAIS_NOM,PAIS_SIGLA)
VALUES(1,'BRASIL','BR');
INSERT INTO TBG_PAIS (PAIS_ID,PAIS_NOM,PAIS_SIGLA)
VALUES(2,'ALEMANHA','AL');
INSERT INTO TBG_PAIS (PAIS_ID,PAIS_NOM,PAIS_SIGLA)
VALUES(3,'COLOMBIA','CO');

--Estado
INSERT INTO TBG_ESTADO (ESTA_ID,PAIS_ID,ESTA_NOM,ESTA_SIGLA)
VALUES(1,1,'DISTRITO FEDERAL','DF');
INSERT INTO TBG_ESTADO (ESTA_ID,PAIS_ID,ESTA_NOM,ESTA_SIGLA)
VALUES(2,1,'SAO PAULO','SP');
INSERT INTO TBG_ESTADO (ESTA_ID,PAIS_ID,ESTA_NOM,ESTA_SIGLA)
VALUES(3,1,'RIO DE JANEIRO','RJ');

--Curso
INSERT INTO TAB_CURSO (CURS_ID,CURS_NOM,CURS_SIGLA)
VALUES(1,'ADMINISTRACAO SISTEMA DE INFORMACAO','ASA');
INSERT INTO TAB_CURSO (CURS_ID,CURS_NOM,CURS_SIGLA)
VALUES(2,'DIREITO','DIR');
INSERT INTO TAB_CURSO (CURS_ID,CURS_NOM,CURS_SIGLA)
VALUES(3,'ENGENHARIA CIVIL','ECI');

--Tipo Acesso
INSERT INTO SEG_TIPO_ACESSO (TACE_ID,TACE_NOM_ACESSO,TACE_DESC)
VALUES(1,'ALUNO',NULL);
 
--Usuario
INSERT INTO seg_usuario (USUA_ID,TACE_ID,USUA_DAT_NASCIMENTO,USUA_DAT_TROCA_SENHA,USUA_EMAIL,USUA_IND_STS,USUA_LOGIN,USUA_NOME,USUA_SENHA)
VALUES(1,1,TO_DATE('1985-08-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,'marcosaig@hotmail.com',1,'MAT00499','MARCO ANTONIO CORREA FIGUEIREDO','p1lYogHoipdsJex439biQw');


INSERT INTO TAB_STATUS_COBRANCA (STCO_ID,STCO_NOM,STCO_IND_VER_PAG,STCO_IND_GER_NOV_COB)
VALUES(1,'A VENCER',1,0);
INSERT INTO TAB_STATUS_COBRANCA (STCO_ID,STCO_NOM,STCO_IND_VER_PAG,STCO_IND_GER_NOV_COB)
VALUES(2,'EM ATRASO',1,1);
INSERT INTO TAB_STATUS_COBRANCA (STCO_ID,STCO_NOM,STCO_IND_VER_PAG,STCO_IND_GER_NOV_COB)
VALUES(3,'PAGO',0,0);

--Tabela Aluno
INSERT INTO TAB_ALUNO (ALUN_ID,USUA_ID,ALUN_CPF,ALUN_NOM,ALUN_DAT_NASC,ALUN_END,ALUN_END_NR,ALUN_END_COMPL,ALUN_BAIRRO,ALUN_CIDADE,ESTA_ID,PAIS_ID,CURS_ID)
VALUES(1,1, '00499561163','MARCO ANTONIO CORREA FIGUEIREDO',TO_DATE('1985-08-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),'QNF',12,'CASA 20','TAGUATINGA NORTE','TAGUATINGA', 1,1,1);

INSERT INTO tab_aluno_cobranca (ALCO_ID,ALUN_ID,ALCO_MES_REF,STCO_ID,ALCO_DAT_VENC,COBN_ID)
VALUES(1,1,12,3,TO_DATE('2016-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1);
INSERT INTO tab_aluno_cobranca (ALCO_ID,ALUN_ID,ALCO_MES_REF,STCO_ID,ALCO_DAT_VENC,COBN_ID)
VALUES(2,1,1,2,TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),2);

INSERT INTO tab_aluno_cobranca (ALCO_ID,ALUN_ID,ALCO_MES_REF,STCO_ID,ALCO_DAT_VENC,COBN_ID)
VALUES(3,2,1,3,TO_DATE('2017-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),3);

INSERT INTO CFT_CONTROLE_COBRANCA (COBN_ID,COBN_DAT_VENC,COBN_DAT_PAG,COBN_VAL_COB,COBN_END_COB,COBN_NOM)
VALUES(1,TO_DATE('2016-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_DATE('2016-12-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1000,'QNF 12 CASA 20','MARCO ANTONIO CORREA FIGUEIREDO');

INSERT INTO CFT_CONTROLE_COBRANCA (COBN_ID,COBN_DAT_VENC,COBN_DAT_PAG,COBN_VAL_COB,COBN_END_COB,COBN_NOM)
VALUES(2,TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),NULL,1000,'QNF 12 CASA 20','MARCO ANTONIO CORREA FIGUEIREDO');

INSERT INTO CFT_CONTROLE_COBRANCA (COBN_ID,COBN_DAT_VENC,COBN_DAT_PAG,COBN_VAL_COB,COBN_END_COB,COBN_NOM)
VALUES(3,TO_DATE('2017-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_DATE('2017-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),1000,'QNF 12 CASA 20','MARCO ANTONIO CORREA FIGUEIREDO');

COMMIT
/
